### ISSUE TITLE
JSON size issues

### ISSUE THREAD

**Issue by withinfocus** [AllenBurgett/hangouts_takeout_to_backupandrestore#10]
Hi there, great script -- I am hoping to get it working for a few years of Hangouts archives.

Any insight into memory or filesize issues with the Python runtime and the load of `Hangouts.json`? I run the script and nothing outputs and I get a `test.xml` with `count="0"`. The size of my JSON file is about 1.6MM lines though so I assume I need to look into more efficient parsing.

**Comment by AllenBurgett** [comment]
1.6MB doesn't seem overly large. The test json (my own archive) I used was about 100MB. Is the python outputting any errors?

**Comment by withinfocus** [comment]
1.6 million rows actually. Same approximate filesize though. No Python (3.7) errors.

**Comment by AllenBurgett** [comment]
How quickly does it complete?

**Comment by withinfocus** [comment]
3-5 seconds.

I am considering a PR with some sort of debug mode but just exploring options at this point.

**Comment by AllenBurgett** [comment]
Yeah, that sounds about right, it doesn't take long to run. The unfortunate reality is that I wouldn't feel comfortable running a debugger of my own on your data. If you can do that and figure out why it doesn't seem to be finding anything to write, then I can help you with any code changes that might be needed.

**Comment by withinfocus** [comment]
Lemme get into an interactive Python environment and I'll report back.

**Comment by withinfocus** [comment]
Threw a quick PR up with a small finding.

Haven't had much time to dig into this but it's looking like I might not have the necessary `participant_data` on my conversations as they were Google account-based and not the SMS bridge (and therefore no phone numbers).

**Comment by AllenBurgett** [comment]
Sorry for the delay. 
So, I assume there might be a way to create a lookup table to convert those conversations to "SMS". If there's some sort of identifying information on each conversation, we could use that as a key to pair up with a phone number. Maybe that's doing too much, but could be an interesting branch.

**Comment by withinfocus** [comment]
Found some time and went back to this one -- please check out the attached PR and lemme know what you think. Would like if you could use some of your test data to see if everything is still working correctly, maybe with a before and after export. Thanks!

**Comment by AllenBurgett** [comment]
Sorry this took so long for me to get to. The last few weeks have been extra hectic. I commented on the code. Let me know if that makes sense.

**Comment by withinfocus** [comment]
I like it, will add.

Also saw this:

https://www.androidpolice.com/2020/05/25/messages-v6-2-rcs-encryption-google-fi-web-features-apk-teardown/

Wondering when this Hangouts conversion effort won't matter should Google solve it ...

**Comment by AllenBurgett** [comment]
Merged associated pull request.
