### ISSUE TITLE
KeyError: 'i18n_data'

### ISSUE THREAD

**Issue by DrewA-P1TT** [AllenBurgett/hangouts_takeout_to_backupandrestore#9]
Thank you so much for this tool.

Seems to fire off, but after a couple seconds...

`Traceback (most recent call last):
  File "jsontoxml.py", line 298, in <module>
    main()
  File "jsontoxml.py", line 291, in main
    count += singlePath(root, thread)
  File "jsontoxml.py", line 18, in singlePath
    is_valid = participant_data[0]['phone_nu
mber']['i18n_data']['is_valid']
KeyError: 'i18n_data'
`

**Comment by AllenBurgett** [comment]
Hey,

I pushed a change that should hopefully help. Pull the new jsontoxml.py file and try it again.

**Comment by DrewA-P1TT** [comment]
WORKS!  Thank you so much!

BTW -- 100MB file with 56k messages. NICE!
